<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Testing" />
    <PackageReference Include="Microsoft.Playwright" />
    <PackageReference Include="Respawn" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\sample\Pizzeria.AppHost\Pizzeria.AppHost.csproj" />
    <ProjectReference Include="..\..\sample\Pizzeria.Auth\Pizzeria.Auth.csproj" />
    <ProjectReference Include="..\..\sample\Pizzeria.Store.Api\Pizzeria.Store.Api.csproj" />
    <ProjectReference Include="..\..\sample\Pizzeria.Store.Data\Pizzeria.Store.Data.csproj" />
    <ProjectReference Include="..\..\sample\Pizzeria.Store.Domain\Pizzeria.Store.Domain.csproj" />
    <ProjectReference Include="..\..\sample\Pizzeria.Store.Web\Pizzeria.Store.Web.csproj" />
  </ItemGroup>

</Project>
