version: '3.4'

services:
  seq:
    container_name: lewee_seq
    image: datalust/seq
    ports:
      - 5341:80
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ./seq:/data
  sqlserver:
    container_name: lewee_sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 5434:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=<YourStrong@Passw0rd!>
    volumes:
      - ./data:/var/opt/mssql/data
  postgres:
    container_name: lewee_postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=<YourStrong@Passw0rd!>
      - POSTGRES_USER=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
