<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Correlate.AspNetCore" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" VersionOverride="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lewee.Common\Lewee.Common.csproj" />
  </ItemGroup>

  <!-- No functionality, just helping setup `Correlate` -->
  <ItemGroup>
    <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" />
  </ItemGroup>

</Project>
