<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Correlate.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lewee.Common\Lewee.Common.csproj" />
  </ItemGroup>

  <!-- No functionality, just helping setup `Correlate` -->
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" />
  </ItemGroup>

</Project>
