<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <!-- CS1591: Missing XML documentation warnings are suppressed for test projects -->
    <!-- CS1587: XML comment placement warnings are suppressed due to test model classes with misplaced XML comments -->
    <NoWarn>$(NoWarn);CS1591;CS1587</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Lewee.Application\Lewee.Application.csproj" />
    <ProjectReference Include="..\Lewee.Tests.Common\Lewee.Tests.Common.csproj" />
  </ItemGroup>

</Project>