<Project>

  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  <Import
    Condition="$(MSBuildProjectName.Contains('.Tests.Unit')) OR $(MSBuildProjectName.Contains('.Tests.Integration'))"
    Project="$([MSBuild]::GetPathOfFileAbove('Tests.props', '$(MSBuildThisFileDirectory)../'))" />

</Project>
