<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Testing" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <ProjectReference Include="..\..\src\Lewee.Infrastructure.HttpClient\Lewee.Infrastructure.HttpClient.csproj" />
    <ProjectReference Include="..\Lewee.Tests.AppHost\Lewee.Tests.AppHost.csproj" />
    <ProjectReference Include="..\Lewee.Tests.Contracts\Lewee.Tests.Contracts.csproj" />
  </ItemGroup>
  
</Project>
