<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Testing" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Lewee.Blazor\Lewee.Blazor.csproj" />
    <ProjectReference Include="..\..\src\Lewee.Infrastructure.AspNet\Lewee.Infrastructure.AspNet.csproj" />
    <ProjectReference Include="..\Lewee.Blazor.Tests.AppHost\Lewee.Blazor.Tests.AppHost.csproj" />
    <ProjectReference Include="..\Lewee.Tests.Common\Lewee.Tests.Common.csproj" />
    <ProjectReference Include="..\Lewee.Tests.Contracts\Lewee.Tests.Contracts.csproj" />
  </ItemGroup>

</Project>
