<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Pizzeria.Configuration.Tests.Unit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Lewee.Auth.Infrastructure.Data\Lewee.Auth.Infrastructure.Data.csproj" />
    <ProjectReference Include="..\Pizzeria.Auth\Pizzeria.Auth.csproj" />
    <ProjectReference Include="..\Pizzeria.Common\Pizzeria.Common.csproj" />
    <ProjectReference Include="..\Pizzeria.ServiceDefaults\Pizzeria.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Pizzeria.Store.Data\Pizzeria.Store.Data.csproj" />
  </ItemGroup>

</Project>
