using FluentAssertions;
using Xunit;

namespace Pizzeria.Store.Domain.Tests;

public sealed class OrderTests
{
    [Fact]
    public void SubmitPickupOrder()
    {
        // Arrange
        var userId = Guid.NewGuid().ToString();
        var margherita = Menu.GetPizzaByName(Menu.PizzaNames.Margherita);
        var fourCheeses = Menu.GetPizzaByName(Menu.PizzaNames.QuattroFormaggi);
        var now = DateTime.UtcNow;

        // Act
        var order = Order.StartNewOrder(userId);

        order.AddPizza(margherita);
        order.AddPizza(fourCheeses);
        order.AddPizza(fourCheeses);

        order.SubmitPickupOrder();

        // Assert
        order.Id.Should().NotBeEmpty();
        order.UserId.Should().Be(userId);
        order.SubmittedDateTime.Should().BeCloseTo(now, precision: TimeSpan.FromMilliseconds(500));
        order.DeliveryAddress.Should().BeNull();
        order.Pizzas.Should().HaveCount(2);

        foreach (var item in order.Pizzas)
        {
            item.Id.Should().NotBeEmpty();
            item.OrderId.Should().Be(order.Id);

            if (item.PizzaId == margherita.Id)
            {
                item.Quantity.Should().Be(1);
            }
            else if (item.PizzaId == fourCheeses.Id)
            {
                item.Quantity.Should().Be(2);
            }
            else
            {
                Assert.Fail("Unexpected pizza in the order.");
            }
        }

        order.IsDeliveryOrder.Should().BeFalse();
        order.IsPrepared.Should().BeFalse();
        order.PreparedDateTime.Should().BeNull();
        order.IsCompleted.Should().BeFalse();
        order.CompletedDateTime.Should().BeNull();
    }

    [Fact]
    public void OrderPizza_Should_Have_Valid_Id_When_Created()
    {
        // Arrange
        var userId = Guid.NewGuid().ToString();
        var margherita = Menu.GetPizzaByName(Menu.PizzaNames.Margherita);
        var order = Order.StartNewOrder(userId);

        // Act
        order.AddPizza(margherita);

        // Assert
        var orderPizza = order.Pizzas.Single();
        orderPizza.Id.Should().NotBeEmpty();
        orderPizza.Id.Should().NotBe(Guid.Empty);

        // Verify that the ID was generated by the AuditableRecord constructor, not explicitly set
        // This ensures EF Core will track it as Added rather than Modified
        orderPizza.OrderId.Should().Be(order.Id);
        orderPizza.PizzaId.Should().Be(margherita.Id);
        orderPizza.Quantity.Should().Be(1);
    }
}
