<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Correlate.DependencyInjection" />
    <PackageReference Include="Flurl" />
    <PackageReference Include="Fluxor.Blazor.Web.ReduxDevTools" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
    <PackageReference Include="Refit.HttpClientFactory" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lewee.Common\Lewee.Common.csproj" />
    <ProjectReference Include="..\Lewee.Infrastructure.AspNet\Lewee.Infrastructure.AspNet.csproj" />
    <ProjectReference Include="..\Lewee.StateManagement\Lewee.StateManagement.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Lewee.Blazor.Tests.Integration</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
  
</Project>
