<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!--
      Don't release because it's not working.
      Package upgrades without appropriate tests are probably the cause.
    -->
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Correlate.DependencyInjection" />
    <PackageReference Include="Fluxor.Blazor.Web.ReduxDevTools" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lewee.Contracts\Lewee.Contracts.csproj" />
    <ProjectReference Include="..\Lewee.Shared\Lewee.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" />
  </ItemGroup>
  
</Project>
