<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Correlate.AspNetCore" />
    <PackageReference Include="Microsoft.Azure.SignalR.Management" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" VersionOverride="1.18.0" />
    <ProjectReference Include="..\Lewee.Application\Lewee.Application.csproj" />
  </ItemGroup>

</Project>
