<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Correlate.AspNetCore" />
    <PackageReference Include="Microsoft.Azure.SignalR.Management" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lewee.Application\Lewee.Application.csproj" />
  </ItemGroup>

</Project>
