<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Correlate.AspNetCore" />
    <PackageReference Include="FreeMediator" />	
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lewee.Application\Lewee.Application.csproj" />
    <ProjectReference Include="..\Lewee.Contracts\Lewee.Contracts.csproj" />
  </ItemGroup>

</Project>
