name: 'get-version'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Detect Latest Tag
      id: latest-tag
      shell: bash
      run: |
        latest_tag=$(git describe --tags --abbrev=0)
        echo "::set-output name=tag::$latest_tag"