name: 'set-version'
inputs:
  version:
    required: true
    default: '0.0.1'
runs:
  using: 'composite'
  steps:
    - name: Set Version
      shell: bash
      run: |
        sed -i 's/0.0.1/${{ steps.version.outputs.latest-tag }}/g' Directory.Build.props
