<Project Sdk="Microsoft.NET.Sdk">
  
  <ItemGroup>
    <PackageReference Include="FastEndpoints" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Lewee.Application\Lewee.Application.csproj" />
    <ProjectReference Include="..\Lewee.Infrastructure.Correlate\Lewee.Infrastructure.Correlate.csproj" />
  </ItemGroup>
  
</Project>
