<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lewee.Application\Lewee.Application.csproj" />
    <ProjectReference Include="..\Lewee.Common\Lewee.Common.csproj" />
  </ItemGroup>

</Project>
