<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MediatR.Contracts" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lewee.Common\Lewee.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Lewee.Infrastructure.Data</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
