<Project Sdk="Microsoft.NET.Sdk.Razor">

  <ItemGroup>
    <PackageReference Include="Fluxor.Blazor.Web" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="MudBlazor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pizzeria.Store.StateManagement\Pizzeria.Store.StateManagement.csproj" />
  </ItemGroup>

</Project>
