<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="bunit.web" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" VersionOverride="9.0.16" />
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\sample\Pizzeria.Store.StateManagement\Pizzeria.Store.StateManagement.csproj" />
  </ItemGroup>

</Project>
