<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Correlate.DependencyInjection" />
    <PackageReference Include="Fluxor.Blazor.Web.ReduxDevTools" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lewee.Contracts\Lewee.Contracts.csproj" />
    <ProjectReference Include="..\Lewee.Shared\Lewee.Shared.csproj" />
  </ItemGroup>

</Project>
