<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Correlate.DependencyInjection" />
    <PackageReference Include="Fluxor.Blazor.Web.ReduxDevTools" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lewee.Application\Lewee.Application.csproj" />
  </ItemGroup>

</Project>
