<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Correlate.DependencyInjection" />
    <PackageReference Include="Fluxor.Blazor.Web.ReduxDevTools" />
  <PackageReference Include="Microsoft.Extensions.Configuration.Binder" VersionOverride="10.0.7" />
  <PackageReference Include="Microsoft.Extensions.Http" VersionOverride="9.0.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lewee.Common\Lewee.Common.csproj" />
  </ItemGroup>

</Project>
