on:
  workflow_call:
    inputs:
      is-pr:
        required: false
        type: boolean
  
jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.*
    - name: Install Dependencies
      run: dotnet restore ./Lewee-CI.sln --nologo
    - name: Build
      run: dotnet build ./Lewee-CI.sln --configuration Release --no-restore --nologo
    - name: Create SQL Server Container
      run: docker compose -f ./docker-compose.ci.yml up
    - name: Test
      run: dotnet test ./Lewee-CI.sln --configuration Release --no-build --nologo --settings coverage.runsettings --results-directory ./coverage
    - name: Tear Down SQL Server Container
      run: docker compose -f ./docker-compose.ci.yml down
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      if: ${{ inputs.is-pr == true }}
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both
    #- name: Add Coverage PR Comment
    #  uses: marocchino/sticky-pull-request-comment@v2
    #  if: ${{ inputs.is-pr == true }}
    #  with:
    #    recreate: true
    #    path: code-coverage-results.md
    #- name: Pack
    #  run: dotnet pack ./Lewee-Pack.sln --configuration Release --no-restore --nologo
