on:
  workflow_call:
    inputs:
      is-pr:
        required: false
        type: boolean

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.*

      - name: Install Aspire Workload
        run: dotnet workload install aspire

      - name: Install HTTPS development certificate
        run: dotnet dev-certs https --trust
  
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: '6.0.x'
          preferLatestVersion: true
          includePrerelease: true

      - name: Determine Version
        id: version
        uses: gittools/actions/gitversion/execute@v3.1.11
        with:
          useConfigFile: true

      - name: Install Dependencies
        run: dotnet restore ./lewee.sln --nologo

      - name: Build
        run: dotnet build ./lewee.sln --configuration Release --no-restore --nologo

      - name: Test
        run: dotnet test ./lewee.sln --configuration Release --no-build --nologo --settings coverage.runsettings --results-directory ./coverage

      - name: Install ReportGenerator
        if: ${{ inputs.is-pr == true }}
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Generate Coverage Report
        if: ${{ inputs.is-pr == true }}
        run: |
          reportgenerator \
            -reports:"coverage/**/coverage.cobertura.xml" \
            -targetdir:"coverage-report" \
            -reporttypes:"MarkdownSummary;Cobertura" \
            -verbosity:"Warning"

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ inputs.is-pr == true }}
        with:
          recreate: true
          path: coverage-report/Summary.md

      - name: Check Diff Coverage (90% threshold)
        if: ${{ inputs.is-pr == true }}
        uses: 5monkeys/cobertura-action@master
        with:
          path: coverage/**/coverage.cobertura.xml
          minimum_coverage: 90
          fail_below_threshold: true
          show_missing: false
          show_branch: false
          show_class_names: false
          only_changed_files: true

      - name: Pack
        run: dotnet pack ./lewee.sln --configuration Release --nologo /p:PackageVersion=${{ steps.version.outputs.fullSemVer }} --output ./output

      - name: Publish to NuGet
        run: dotnet nuget push ./output/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        if: github.ref == 'refs/heads/main'
