on:
  workflow_call:
  
jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.202
    - name: Install Dependencies
      run: dotnet restore ./Lewee-CI.sln --nologo
    - name: Build
      run: dotnet build ./Lewee-CI.sln --configuration Release --no-restore --nologo
    - name: Create SQL Server Container
      run: docker compose -f ./docker-compose.ci.yml up
    - name: Test
      run: dotnet test ./Lewee-CI.sln --configuration Release --no-build --nologo --collect "XPlat Code Coverage" --results-directory ./coverage
    - name: Tear Down SQL Server Container
      run: docker compose -f ./docker-compose.ci.yml down
    - name: Pack
      run: dotnet pack ./Lewee-Pack.sln --configuration Release --no-restore --nologo
