name: CI Build

on:
  workflow_dispatch:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Version
      id: version
      uses: codacy/git-version@2.7.1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.202
    - name: Install Dependencies
      run: dotnet restore ./Lewee-CI.sln --nologo
    - name: Build
      run: dotnet build ./Lewee-CI.sln --configuration Release --no-restore --nologo
    - name: Create SQL Server Container
      run: docker compose -f ./docker-compose.ci.yml up
    # - name: Test
    #   run: dotnet test ./Lewee-CI.sln --configuration Release --no-build --nologo --collect "XPlat Code Coverage" --results-directory ./coverage
    - name: Test
      run: dotnet test ./Lewee-CI.sln --configuration Release --no-build --nologo
    - name: Tear Down SQL Server Container
      run: docker compose -f ./docker-compose.ci.yml down
    # - name: Code Coverage Report
    #   uses: irongut/CodeCoverageSummary@v1.3.0
    #   with:
    #     filename: coverage/**/coverage.cobertura.xml
    #     badge: true
    #     format: markdown
    #     hide_branch_rate: false
    #     hide_complexity: false
    #     indicators: true
    #     output: both
    # - name: Add Coverage PR Comment
    #   uses: marocchino/sticky-pull-request-comment@v2
    #   if: github.event_name == 'pull_request'
    #   with:
    #     recreate: true
    #     path: code-coverage-results.md
    - name: Pack
      run: dotnet pack ./Lewee-CI.sln --configuration Release --no-restore /p:PackageVersion=${{ steps.version.outputs.version }} --output ./output
    - name: Install NuGet
      uses: NuGet/setup-nuget@v1.0.5
      if: ${{ github.ref == 'refs/heads/master' }}
    - name: Publish to NuGet
      run: nuget push ./output/*.nupkg -ApiKey ${{ secrets.NUGET_API_KEY }} -Source https://api.nuget.org/v3/index.json
      if: ${{ github.ref == 'refs/heads/master' }}
