name: Pack Test

on:
  workflow_dispatch:

jobs:
  packTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.*
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
          preferLatestVersion: true
          includePrerelease: false
      - name: Determine Version
        id: version
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
      - name: Pack
        run: dotnet pack ./pack.sln --configuration Release --nologo /p:PackageVersion=${{ steps.version.outputs.fullSemVer }}