name: Pack Test

on:
  workflow_dispatch:

jobs:
  packTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Determine Version
        id: version
        shell: bash
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "::set-output name=latest-tag::$latest_tag"
      - name: Set Version
        uses: Mudlet/xmlstarlet-action@master
        with:
          args: ed -L --update "//Project/PropertyGroup/Version" -v ${{ steps.version.outcome.latest_tag }} Directory.Build.props
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.*
      - name: Pack
        run: dotnet pack ./pack.sln --configuration Release --nologo /p:PackageVersion=${{ steps.version.outputs.latest-tag }}