name: Pack Test

on:
  workflow_dispatch:

jobs:
  packTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Determine Version
        id: version
        shell: bash
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "name=latest-tag::$latest_tag" >> $GITHUB_OUTPUT
      - name: Set Version
        shell: bash
        run: |
          sed -i 's/0.0.1/${{ steps.version.outputs.latest-tag }}/g' Directory.Build.props
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.*
      - name: Pack
        run: dotnet pack ./pack.sln --configuration Release --nologo /p:PackageVersion=${{ steps.version.outputs.latest-tag }}