name: PR Checks
on:
  pull_request:
    branches: [ main, develop ]

jobs:
  buildAndTest:
    uses: ./.github/workflows/build-and-test.yml
  #testCoverage:
  #  uses: ./.github/workflows/test-coverage.yml
      