name: Publish

on:
  workflow_run:
    workflows: [ "CI Build" ]
    types:
      - completed
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Determine Version
      id: version
      uses: ./.github/actions/get-version
    - name: Set Version
      uses: ./.github/actions/set-version
      with:
        version: $steps.version.outputs.latest-tag
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.*
    - name: Pack
      run: dotnet pack ./pack.sln --configuration Release --nologo /p:PackageVersion=${{ steps.version.outputs.latest-tag }}
    - name: Publish to NuGet
      run: dotnet nuget push ./output/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate