name: Publish

on:
  workflow_run:
    workflows: [ "CI Build" ]
    types:
      - completed
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get Latest Tag
      id: get_latest_tag
      run: |
        latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
        echo "latest_tag=${latest_tag}" >> "$GITHUB_ENV"
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.*
    - name: Pack
      run: dotnet pack ./pack.sln --configuration Release --nologo /p:PackageVersion=$latest_tag --output ./output
    - name: Publish to NuGet
      run: dotnet nuget push ./output/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate