name: Publish

on: [ workflow_dispatch ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
        preferLatestVersion: true
    - name: Determine Version
      id: version
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.*
    - name: Pack
      run: dotnet pack ./Lewee-Pack.sln --configuration Release --nologo /p:PackageVersion=${{ steps.version.outputs.fullSemVer }} --output ./output
    - name: Install NuGet
      uses: NuGet/setup-nuget@v1.0.5
    - name: Publish to NuGet
      run: nuget push ./output/*.nupkg -ApiKey ${{ secrets.NUGET_API_KEY }} -Source https://api.nuget.org/v3/index.json