on:
  workflow_call:

jobs:
  setVersion:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_latest_tag.latest_tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "::set-output name=latest_tag::${latest_tag}"
      - name: Set Version
        uses: Mudlet/xmlstarlet-action@master
        with:
          args: ed -L --update "//Project/PropertyGroup/Version" -v ${{ steps.get_latest_tag.latest_tag }} Directory.Build.props
