on:
  workflow_call:
    inputs:
      is-pr:
        required: false
        type: boolean

jobs:
  testCoverage:
    runs-on: ubuntu-latest
    steps:
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        recreate: true
        path: code-coverage-results.md